### ISSUE TITLE
Having trouble with mlcp

### ISSUE THREAD

**Issue by willipwolf** [wpaven/hands-on-data-modeling#89]
Can you tell me why I am getting this error when I run the data load first step ?

c:\hands-on-data-modeling-master\unit-01\mlcp>C:\mlcp\bin\mlcp.bat -options_file employees.cfg
16/06/15 06:49:41 INFO contentpump.LocalJobRunner: Content type: XML
16/06/15 06:49:42 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
16/06/15 06:49:42 ERROR contentpump.LocalJobRunner: Error checking output specification:
16/06/15 06:49:42 ERROR contentpump.LocalJobRunner: java.io.IOException: com.marklogic.xcc.exceptions.ServerResponseException: Query evaluation request rejected (400, Bad Request). Is this an XDBC server?
 [Session: user=amy, cb={default} [ContentSource: user=amy, cb={none} [provider: address=localhost/127.0.0.1:8080, pool=0/64]]]
 [Client: XCC/8.0-5]

**Comment by dmcassel** [comment]
It looks like port 8080 isn't hosting an XDBC server, which suggests one of two things to me:
1. Did you run the [setup script](https://github.com/wpaven/hands-on-data-modeling/tree/master/setup)? 
2. If you did, there's most likely a port conflict with something else, perhaps Apache Tomcat. 

To diagnose, try pointing a browser to localhost:8080. You might see something like a Tomcat welcome screen, or something else that isn't coming from MarkLogic. 

If that's the case, your choices are to shut down the other service or to change the ports that MarkLogic uses. You'll need to change the employee-app-server application service to a different port, then change each of the mlcp config files to use that port. Likewise for the CORB jobs.

**Comment by willipwolf** [comment]
Thanks, I did have MarkLogic XDBC replying there but had not checked it.  When I did point my browser at port 8080 it put up a logon box and I was able to authenticate with amy/amy.  That might have been a necessary kick-start, because after I did that manual probe, the mlcp is working !  I appreciate your help.
